var langlibrary={};
if(lang=="en"){
    langlibrary={
        'email_required':'Looks like you forgot to enter the email!',
        'password_required':'Did you forgot to enter the password ?',
        'email_incorrect':'Enter correct email address',
        'like_it':'Like it',
        'dont_like_it':'Don\'t Like it',
        'you_like_this':'You Like This',
        'you_dont_like_this':'You Don\'t Like This',
        'enter_new_password':'Please enter new Password',
        'passwords_must_match':'Password fields must match',
        'name_required':'What should we call You ?',
        'name_required2':'Please enter your Name',
        'birthday_required':'Please enter your birthday',
        'please_select_cuisines':'Please select some cuisines',
        'like':'Like',
        'liked':'Liked',
        'like_some_restaurants':'Like some restaurants',
        'follow':'Follow',
        'following':'Following',
        'follow_some_users':'Please Follow some Users',
        'thank_you':'Thank you',
        'please_select_photo':'Please select Photo',
        'please_add_all_fields':'Please fill all fields',
        'select_bigger_image':'Please select bigger image (Minimum 800px width x 500px height)',
        'select_cuisine':'Select Cuisine',
        'maximum':'Maximum',
        'max_2cuisines':'You can only select two cuisines',
        'restaurantstitle':'Restaurants &amp; Places',
        'sectionstitle':'Sections &amp; Pages',
        'hotelstitle':'Hotels',
        'cuisinestitle':'Cuisines',
        'locationstitle':'Locations',
        'menutitle':'Menu',
        'dishestitle':'Food &amp; Dishes',
        'districtstitle':'Districts',
        'recommendation_choices':'Be the first to recommend this|Recommendation|Recommendations',
        'message_required':'Please enter the Message',
        'select_enquiry':'Please select Enquiry Type',
        'close':'Close',
        'please_select_an_option':'Please select an Option',
        'are_you_sure':'Are you Sure?',
        'please_enter_num':'Please enter your mobile number',
        'event_title_required':'Please enter event title',
        'number_of_guest_required':'Please enter number of guests',
        'event_date_required':'Event date Required',
        'event_time_req':'Please select time of the event',
        'select_event_type':'Please select event type',
        'select_budget':'Please select budget',
        'select_event_venue':'Select Event Venue',
        'select_meal_courses':'Select some Meal Courses',
        'select_serving_style':'Select serving style',
        'select_event_location':'Select event location',
        'select_dining_setup':'Select dining setup',
        'agree_catering_terms':'You\'ve to agree to the terms and conditions',
        'please_drag_location':'Please move the marker to correct location',
        'Worst' : 'Worst',
        'Poor':'Poor',
        'Average':'Average',
        'Good':'Good',
        'Excellent':'Excellent',
    }
}
if(lang=="ar"){
    langlibrary={
        'email_required':'يبدو انك نسيت ان تدخل عنوان بريدك الإلكتروني',
        'password_required':'هل نسيت إدخال كلمة المرور ؟',
        'email_incorrect':' أدخل عنوان بريدك الإلكتروني الصحيح',
        'like_it':'يعجبني',
        'dont_like_it':'لا يعجبني',
        'you_like_this':'يعجبك هذا',
        'you_dont_like_this':'لا يعجبك هذا',
        'enter_new_password':'فضلاً أدخل كلمة المرور الجديدة',
        'passwords_must_match':'يجب ان تتطابق الحقول في كلمة المرور',
        'name_required':'ماذا تحب أن يكون إسمك؟',
        'name_required2':'فضلاً أدخل إسمك',
        'birthday_required':'فضلاً أدخل تاريخ الميلاد',
        'please_select_cuisines':'إختر نوع المطبخ المفضل لديك',
        'like':'أعجبني',
        'liked':'معجب بـ',
        'like_some_restaurants':'إختر بعض المطاعم المفضلة لديك',
        'follow':'تابع',
        'following':'متابع لـ',
        'follow_some_users':'فضلاً قم بمتابعة بعض المستخدمين',
        'thank_you':'شكراً',
        'please_select_photo':'فضلاً إختر صورة',
        'please_add_all_fields':'فضلاً قم بملئ كل الحقول',
        'select_bigger_image':'فضلاً إختر صورة بحجم أكبر (الحد الأدنى 800px بحد العرض × 500px الارتفاع)',
        'select_cuisine':'إختر نوع المطبخ',
        'maximum':'الحد الأعلى',
        'max_2cuisines':'لا يمكن إختيار أكثر من نوعين من المطابخ',
        'restaurantstitle':'مطاعم و أماكن مميزة',
        'sectionstitle':'الأقسام و الصفحات',
        'hotelstitle':'فنادق',
        'cuisinestitle':'انواع المطابخ',
        'locationstitle':'مواقع جغرافية',
        'menutitle':'قائمة الطعام',
        'dishestitle':'أكلات و أطباق',
        'districtstitle':'مناطق و أحياء',
        'recommendation_choices':'كن اول الموصين بـ | توصية | توصيات',
        'message_required':'فضلاً أدخل الرسالة',
        'select_enquiry':'فضلاً أدخل نوعية الإستفسار',
        'close':'إغلاق',
        'please_select_an_option':'فضلاً إختر احد الخيارات التالية',
        'are_you_sure':'هل أنت متأكد؟',
        'please_enter_num':'الرجاء إدخال رقم الجوال',
        'event_title_required':' عنوان المناسبة',
        'number_of_guest_required':'عدد الضيوف',
        'event_date_required':'تاريخ إقامة المناسبة',
        'event_time_req':' توقيت إقامة المناسبة' ,
        'select_event_type':'نوع المناسبة',
        'select_budget':'حدد الميزانية المخصصة',
        'select_event_venue':'مكان إقامة المناسبة',
        'select_meal_courses':'اختر بعض الوجبات',
        'select_serving_style':'حدد نمط تقديم الطعام',
        'select_event_location':'اختر موقع المناسبة',
        'select_dining_setup':'اختر نظام الإطعام',
        'agree_catering_terms':'يتوجب عليك احترام القوانين و الشروط',
        'please_drag_location':'يرجى نقل علامة لتصحيح موقع',
        'Worst' : 'سئ جدا',
        'Poor':'سئ',
        'Average':'متوسط',
        'Good':'جيد',
        'Excellent':'ممتاز',

    }
}