<?php 
return array(
	'policy_summary'=>'Policy summary',
	'summary_sub_head'=>'Personal Data collected for the following purposes and using the following services:',
	'summary_social'=>'<h3>Access to social networks accounts</h3><ul><li><h3>Access to the Facebook account</h3><p>Permissions: About Me, Birthday, Current City, Email and Publish App Activity</p></li></ul>',
	'summary_contact'=>'<h3>Contacting the User</h3><ul><li><h3>Contact form</h3><p>Personal Data: Email, First Name, Last Name and Phone number</p></li></ul>',
	'summary_analytics'=>'<h3>Analytics</h3><ul><li><h3>Google Analytics</h3><p>Personal Data: Cookie and Usage Data</p></li></ul>',
	'summary_content'=>'<h3>Content commenting</h3><ul><li><h3>Comment system managed directly</h3><p>Personal Data: Email, First Name and Last Name</p></li></ul>',
	'summary_interaction'=>'<h3>Interaction with external social networks and platforms</h3><ul><li><h3>Twitter Tweet button and social widgets</h3><p>Personal Data: Cookie and Usage Data</p></li></ul>',
	'summary_location'=>'<h3>Location-based interactions</h3><ul><li><h3>Geolocation</h3><p>Personal Data: Geographic position</p></li></ul>',
	'summary_registration'=>'<h3>Registration and authentication</h3><ul><li><h3>Facebook Authentication</h3><p>Personal Data: Various types of Data</p></li><li><h3>Direct registration</h3><p>Personal Data: City, Country, Date of Birth, Email, First Name, Last Name and Password</p></li></ul>',
	'further_head'=>'Further information about Personal Data',
	'further_desc'=>'<h3>Push notifications</h3><p class="more_one"></p><p>This Application may send push notifications to the User.</p><p></p>',
	'contact_desc'=>'<h3>Data owner</h3><p>Azooma Creative - Jeddah, Saudi Arabia, admin@Azooma.co</p>',
	'full_policy'=>'Full policy',
	'full_owner'=>'<h2>Data Controller and Owner</h2><p>Azooma Creative - Jeddah, Saudi Arabia,<br>admin@Azooma.co<br></p>',
	'data_types'=>'<h2>Types of Data collected</h2><p>Among the types of Personal Data that this Application collects, by itself or through third parties, there are: Cookie, Usage Data, First Name, Last Name, Phone number, Email, Geographic position, Date of Birth, Password, Country and City.</p><p>Other Personal Data collected may be described in other sections of this privacy policy or by dedicated explanation text contextually with the Data collection.<br>The Personal Data may be freely provided by the User, or collected automatically when using this Application.<br>Any use of Cookies - or of other tracking tools - by the Application or by the owners of third party services used by this Application, unless stated otherwise, serves to identify Users and remember their preferences, for the sole purpose of providing the service required by the User.<br>Failure to provide certain Personal Data may make it impossible for this Application to provide its services.</p><p>The User assumes responsibility for the Personal Data of third parties published or shared through this Application and declares to have the right to communicate or broadcast them, thus relieving the Data Controller of all responsibility.</p>',
	'mode_processing'=>'<h2>Mode and place of processing the Data</h2><h3>Method of processing</h3><p>The Data Controller processes the Data of Users in proper manner and shall take appropriate security measures to prevent unauthorized access, disclosure, modification or unauthorized destruction of the Data.<br>Access to the Data may be available to Data Processors such as employees involved with the processing or to external parties providing services to the Data Controller, third party technical service providers, mail carriers, hosting providers, IT companies, communication agencies. The updated list of these parties may be requested from the Data Controller at any time.</p><h3>Place</h3><p>The Data is processed at the Data Controller headquarters, unless stated otherwise in the rest of this document.</p><h3>Conservation Time</h3><p>The Data is kept for the time necessary to provide the service requested by the User, or stated by the purposes outlined in this document, and the User can always request the Data Controller for their suspension or removal.</p>',
	'collected_data_use'=>'<h2>The use of the collected Data</h2><p>The Data concerning the User is collected to allow the Application to provide its services, as well as for the following purposes: Analytics, Access to social networks accounts, Contacting the User, Interaction with external social networks and platforms, Content commenting, Location-based interactions and Registration and authentication.</p><p>The Personal Data used for each purpose is outlined in the specific sections of this document.</p>',
	'facebook_permissions'=>'<h2>Facebook permissions asked by this Application</h2><p>This Application may ask some Facebook permissions allowing it to perform actions with the User\'s Facebook account and to retrieve information, including Personal Data, from it.</p><p>For more information about the following permissions, refer to the <a href="https://developers.facebook.com/docs/authentication/permissions/" target="_blank">Facebook permissions documentation</a> and to the <a href="https://www.facebook.com/about/privacy/" target="_blank">Facebook privacy policy</a>.</p><p>The permissions asked are the following:</p><h3>Basic information</h3><p>By default, this includes certain User’s Data such as id, name, picture, gender, and their locale. Certain connections of the User, such as the Friends, are also available. If the user has made more of their data public, more information will be available.</p><h3>About Me</h3><p>Provides access to the \'About Me\' section of the profile</p><h3>Birthday</h3><p>Provides access to the birthday</p><h3>Current City</h3><p>Provides access to the user\'s current location</p><h3>Email</h3><p>Provides access to the user\'s primary email address</p><h3>Publish App Activity</h3><p>Allows the app to publish to the Open Graph using&nbsp;Built-in Actions, Achievements,&nbsp;Scores, or&nbsp;Custom Actions. The app can also publish other activity which is detailed in the Facebook\'s Publishing Permissions&nbsp;document.</p>',
	'detailed_head'=>'Detailed information on the processing of Personal Data',
	'detailed_desc'=>'Personal Data is collected for the following purposes and using the following services:',
	'detailed_social_head'=>'Access to social networks accounts',
	'detailed_social_desc'=>'<p>These services allow this Application to access Data from your social networks accounts and perform actions with it.<br>These services are not activated automatically, but require explicit authorization by the User.</p><h4>Access to the Facebook account (This Application)</h4><p>This service allows this Application to connect with the User\'s account on the Facebook social network, provided by Facebook Inc.</p><p>Permissions asked: About Me, Birthday, Current City, Email and Publish App Activity.</p><p>Place of processing: USA – <a href="http://www.facebook.com/privacy/explanation.php" target="_blank">Privacy Policy</a></p>',
	'detailed_analytics_head'=>'Analytics',
	'detailed_analytics_desc'=>'<p>The services contained in this section enable the Owner to monitor and analyze web traffic and can be used to keep track of User behavior.</p><h4>Google Analytics (Google)</h4><p>Google Analytics is a web analysis service provided by Google Inc. (“Google”). Google utilizes the Data collected to track and examine the use of this Application, to prepare reports on its activities and share them with other Google services.<br>Google may use the Data collected to contextualize and personalize the ads of its own advertising network.</p><p>Personal Data collected:Cookie and Usage Data.</p><p>Place of processing: USA – <a href="http://www.google.com/intl/en/policies/privacy/" target="_blank">Privacy Policy</a></p>',
	'detailed_contact_head'=>'Contacting the User',
	'detailed_contact_desc'=>'<h4>Contact form (This Application)</h4><p>By filling in the contact form with their Data, the Users authorizes this Application to use these details to reply to requests for information, quotes or any other kind of request as indicated by the form’s header.</p><p>Personal Data collected: Email, First Name, Last Name and Phone number.</p><p></p>',
	'detailed_content_head'=>'Content commenting',
	'detailed_content_desc'=>'<p>Content commenting services allow Users to make and publish their comments on the contents of this Application.<br>Depending on the settings chosen by the Owner, Users may also leave anonymous comments. If there is an email address among the Personal Data provided by the User, it may be used to send notifications of comments on the same content. Users are responsible for the content of their own comments.<br>If a content commenting service provided by third parties is installed, it may still collect web traffic data for the pages where the comment service is installed, even when users do not use the content commenting service.</p><h4>Comment system managed directly (This Application)</h4><p>This Application has its own internal content comment system.</p><p>Personal Data collected: Email, First Name and Last Name.</p><p></p>',
	'detailed_interaction_head'=>'Interaction with external social networks and platforms',
	'detailed_interaction_desc'=>'<p>These services allow interaction with social networks or other external platforms directly from the pages of this Application.<br>The interaction and information obtained by this Application are always subject to the User’s privacy settings for each social network.<br>If a service enabling interaction with social networks is installed it may still collect traffic data for the pages where the service is installed, even when Users do not use it.</p><h4>Twitter Tweet button and social widgets (Twitter)</h4><p>The Twitter Tweet button and social widgets are services allowing interaction with the Twitter social network provided by Twitter Inc.</p><p>Personal Data collected: Cookie and Usage Data.</p><p>Place of processing: USA – <a href="http://twitter.com/privacy" target="_blank">Privacy Policy</a></p>',
	'detailed_location_head'=>'Location-based interactions',
	'detailed_location_desc'=>'<h4>Geolocation (This Application)</h4><p>This Application may collect, use, and share User location Data in order to provide location-based services.<br>Most browsers and devices provide tools to opt out from this feature by default. If explicit authorization has been provided, the User’s location data may be tracked by this Application.</p><p>Personal Data collected: Geographic position.</p><p></p>',
	'detailed_registration_head'=>'Registration and authentication',
	'detailed_registration_desc'=>'<p>By registering or authenticating, Users allow this Application to identify them and give them access to dedicated services.<br>Depending on what is described below, third parties may provide registration and authentication services.<br>In this case, this Application will be able to access some Data, stored by these third party services, for registration or identification purposes.</p><h4>Facebook Authentication (Facebook)</h4><p>Facebook Authentication is a registration and authentication service provided by Facebook Inc. and is connected to the Facebook social network.</p><p>Personal Data collected: Various types of Data.</p><p>Place of processing: USA – <a href="http://www.facebook.com/help/?page=229348490415842" target="_blank">Privacy Policy</a></p><h4>Direct registration (This Application)</h4><p>The User registers by filling out the registration form and providing the Personal Data directly to this Application.</p><p>Personal Data collected: City, Country, Date of Birth, Email, First Name, Last Name and Password.</p><p></p>',
	'further_info_head'=>'Further information about Personal Data',
	'further_push_head'=>'Push notifications',
	'further_push_desc'=>'<p></p><p>This Application may send push notifications to the User.</p><p></p>',
	'add_info_head'=>'Additional information about Data collection and processing',
	'add_info_desc'=>'<h3>Legal Action</h3><p>The User\'s Personal Data may be used for legal purposes by the Data Controller, in Court or in the stages leading to possible legal action arising from improper use of this Application or the related services.</p><h3>Additional Information about User\'s Personal Data</h3><p>In addition to the information in this privacy policy, this Application may provide the User with contextual information concerning particular services or the collection and processing of Personal Data.</p><h3>System Logs and Maintenance</h3><p>For operation and maintenance purposes, this Application and any third party services may collect files that record interaction with this Application (System Logs) or use for this purpose other Personal Data (such as IP Address).</p><h3>Information not contained in this policy</h3><p>More details concerning the collection or processing of Personal Data may be requested from the Data Controller at any time at its contact information.</p><h3>The rights of Users</h3><p>Users have the right, at any time, to know whether their Personal Data has been stored and can consult the Data Controller to learn about their contents and origin, to verify their accuracy or to ask for them to be supplemented, cancelled, updated or corrected, or for their transformation into anonymous format or to block any data held in violation of the law, as well as to oppose their treatment for any and all legitimate reasons. Requests should be sent to the Data Controller at the contact information set out above.</p><h3>Changes to this privacy policy</h3><p>The Data Controller reserves the right to make changes to this privacy policy at any time by giving notice to its Users on this page. It is strongly recommended to check this page often, referring to the date of the last modification listed at the bottom. If a User objects to any of the changes to the Policy, the User must cease using this Application and can request the Data Controller to erase the Personal Data. Unless stated otherwise, the then-current privacy policy applies to all Personal Data the Data Controller has about Users.</p>',
	'definintion_head'=>'Definitions and legal references',
	'definintion_desc'=>'<h4>Personal Data (or Data)</h4><p>Any information regarding a natural person, a legal person, an institution or an association, which is, or can be, identified, even indirectly, by reference to any other information, including a personal identification number.</p><h4>Usage Data</h4><p>Information collected automatically from this Application (or third party services employed in this Application ), which can include: the IP addresses or domain names of the computers utilized by the Users who use this Application, the URI addresses (Uniform Resource Identifier), the time of the request, the method utilized to submit the request to the server, the size of the file received in response, the numerical code indicating the status of the server\'s answer (successful outcome, error, etc.), the country of origin, the features of the browser and the operating system utilized by the User, the various time details per visit (e.g., the time spent on each page within the Application) and the details about the path followed within the Application with special reference to the sequence of pages visited, and other parameters about the device operating system and/or the User\'s IT environment.</p><h4>User</h4><p>The individual using this Application, which must coincide with or be authorized by the Data Subject, to whom the Personal Data refer.</p><h4>Data Subject</h4><p>The legal or natural person to whom the Personal Data refers to.</p><h4>Data Processor</h4><p>The natural person, legal person, public administration or any other body, association or organization authorized by the Data Controller to process the Personal Data in compliance with this privacy policy.</p><h4>Data Controller (or Application Owner, or Owner)</h4><p>The natural person, legal person, public administration or any other body, association or organization with the right, also jointly with another Data Controller, to make decisions regarding the purposes, and the methods of processing of Personal Data and the means used, including the security measures concerning the operation and use of this Application. The Data Controller, unless otherwise specified, is the Owner of this Application.</p><h4>This Application</h4><p>The hardware or software tool by which the User Personal Data is collected.</p><h4>Cookie</h4><p>Small piece of data stored in the User\'s device.</p><hr><h4>Legal information</h4><p>Notice to European Users: this privacy statement has been prepared in fulfillment of the obligations under Art. 10 of EC Directive n. 95/46/EC, and under the provisions of Directive 2002/58/EC, as revised by Directive 2009/136/EC, on the subject of Cookies.</p><p>This privacy policy is solely about this Application.</p>',











);