<?php

$raw_countries = Country::orderBy('id', 'DESC')->get();
$countries = array();
if (is_object($raw_countries)) {
    foreach ($raw_countries as $arr) {
        $countries[$arr->id] = $arr->name;
    }
}
//#for online uploadpath => /home/diner/public_html/uploads,
return array(
    'uploadpath' => './uploads',   
    'uploadurl' => 'http://localhost/azooma-dev/uploads/', 
    'sitename' => 'Azooma',
    'default' => array(
        'name' => 'Azooma',
        'nameAr' => 'Azooma',
        'country' => 'Saudi Arabia',
        'email' => 'info@azooma.co',
        'twitter' => '',
        'facebook' => '',
        'linkedin' => '',
        'youtube' => '',
        'instagram' => '',
        'address' => 'City Center',
        'addressAr' => 'City Center',
        'currency' => 'SAR',
        'tel' => '0564636425',
        'fax' => '0564636425',
        'mobile' => '0564636425',
        'teamEmails' => array("info@azooma.co", "data@azooma.co", "aas@azooma.co", "admin@azooma.co", 'ha@azooma.co', "fasil@azooma.co"),
    ),
    'saudi-arabia' => array(
        'name' => 'Sufrati',
        'nameAr' => 'Sufrati',
        'country' => 'Saudi Arabia',
        'email' => 'info@azooma.co',
        'twitter' => '',
        'facebook' => '',
        'linkedin' => '',
        'youtube' => '',
        'instagram' => '',
        'address' => 'City Center',
        'addressAr' => 'City Center',
        'currency' => 'SAR',
        'tel' => '0564636425',
        'fax' => '0564636425',
        'mobile' => '0564636425',
        'teamEmails' => array("info@azooma.co", "data@azooma.co", "aas@azooma.co", "admin@azooma.co", 'ha@azooma.co', "fasil@azooma.co"),
    ),
    'united-kingdom' => array(
        'name' => 'Sufrati',
        'nameAr' => 'Sufrati',
        'country' => 'United Kingdom',
        'email' => 'info@azooma.co',
        'twitter' => '',
        'facebook' => '',
        'linkedin' => '',
        'youtube' => '',
        'instagram' => '',
        'address' => 'City Center',
        'addressAr' => 'City Center',
        'currency' => 'SAR',
        'tel' => '0564636425',
        'fax' => '0564636425',
        'mobile' => '0564636425',
        'teamEmails' => array("info@azooma.co", "data@azooma.co", "aas@azooma.co", "admin@azooma.co", 'ha@azooma.co', "fasil@azooma.co"),
    ),
    'lebanon' => array(
        'name' => 'Sufrati-Lebanon',
        'nameAr' => 'Sufrati',
        'country' => 'Saudi Arabia',
        'email' => 'info@azooma.co',
        'twitter' => '',
        'facebook' => '',
        'linkedin' => '',
        'youtube' => '',
        'instagram' => '',
        'address' => 'City Center',
        'addressAr' => 'City Center',
        'currency' => 'SAR',
        'tel' => '0564636425',
        'fax' => '0564636425',
        'mobile' => '0564636425',
        'teamEmails' => array("Haroon" => 'ha@azooma.co'),
    ),
    'countries' => $countries,
    'bannertypes' => array(
        '1' => 'Top Banner (968x98)',
        '2' => 'Side Banner (245xany)',
        '3' => 'Results Banner (657x50)',
        '4' => 'Popular Results Side Banner (265x146)',
    )
);